# Generated by Django 4.2.7 on 2023-12-20 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderpic',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
