# Generated by Django 4.2.7 on 2023-12-20 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_sliderpic_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, upload_to='News_image/')),
                ('text', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='sliderpic',
            name='image',
            field=models.ImageField(upload_to='sliders/'),
        ),
    ]
