# Generated by Django 4.2.7 on 2023-12-21 02:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='name_tk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='table_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='table_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='table_tk',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
