# Generated by Django 4.2.7 on 2023-12-21 02:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_table_name_en_table_name_ru_table_name_tk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermiTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mintable', ckeditor.fields.RichTextField()),
                ('mintable_tk', ckeditor.fields.RichTextField(null=True)),
                ('mintable_ru', ckeditor.fields.RichTextField(null=True)),
                ('mintable_en', ckeditor.fields.RichTextField(null=True)),
            ],
        ),
    ]
